export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNUP_PENDING = 'SIGNUP_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_PENDING = 'LOGIN_PENDING';

export const FETCH_PROFILE_PENDING = 'FETCH_PROFILE_PENDING';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_ERROR = 'FETCH_PROFILE_ERROR';

export const UPDATE_PROFILE_PENDING = 'UPDATE_PROFILE_PENDING';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

// Reset password actions
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

// stock out actions
export const CREATE_MODULES_PENDING = 'CREATE_MODULES_PENDING';
 export const CREATE_MODULES_SUCCESS = 'CREATE_MODULES_SUCCESS';
 export const CREATE_MODULES_ERROR = 'CREATE_MODULES_ERROR';
 export const FETCH_MODULES_SUCCESS = 'FETCH_MODULES_SUCCESS';
 export const FETCH_MODULES_ERROR = 'FETCH_MODULES_ERROR';
 export const FETCH_MODULES_PENDING = 'FETCH_MODULES_PENDING';
export const DELETE_MODULES_ERROR = 'DELETE_MODULES_ERROR';
export const DELETE_MODULES_SUCCESS = 'DELETE_MODULES_SUCCESS';
export const DELETE_MODULES_PENDING = 'DELETE_MODULES_PENDING';
export const UPDATE_MODULES_SUCCESS = 'UPDATE_MODULES_SUCCESS';
export const UPDATE_MODULES_ERROR = 'UPDATE_MODULES_ERROR';
export const UPDATE_MODULES_PENDING = 'UPDATE_MODULES_PENDING';

// stock out actions
export const CREATE_STOCKOUT_PENDING = 'CREATE_STOCKOUT_PENDING';
 export const CREATE_STOCKOUT_SUCCESS = 'CREATE_STOCKOUT_SUCCESS';
 export const CREATE_STOCKOUT_ERROR = 'CREATE_STOCKOUT_ERROR';
 export const FETCH_STOCKOUT_SUCCESS = 'FETCH_STOCKOUT_SUCCESS';
 export const FETCH_STOCKOUT_FAILURE = 'FETCH_STOCKOUT_FAILURE';
 export const FETCH_STOCKOUT_LOADING = 'FETCH_STOCKOUT_LOADING';
export const DELETE_STOCKOUT_FAIL = 'DELETE_STOCKOUT_FAIL';
export const DELETE_STOCKOUT_SUCCESS = 'DELETE_STOCKOUT_SUCCESS';
export const DELETE_STOCKOUT_LOADING = 'DELETE_STOCKOUT_LOADING';
export const UPDATE_STOCKOUT_SUCCESS = 'UPDATE_STOCKOUT_SUCCESS';
export const UPDATE_STOCKOUT_ERROR = 'UPDATE_STOCKOUT_ERROR';
export const UPDATE_STOCKOUT_PENDING = 'UPDATE_STOCKOUT_PENDING';

// stock in actions
export const CREATE_STOCKIN_PENDING = 'CREATE_STOCKIN_PENDING';
 export const CREATE_STOCKIN_SUCCESS = 'CREATE_STOCKIN_SUCCESS';
 export const CREATE_STOCKIN_ERROR = 'CREATE_STOCKIN_ERROR';
 export const FETCH_STOCKIN_SUCCESS = 'FETCH_STOCKIN_SUCCESS';
 export const FETCH_STOCKIN_FAILURE = 'FETCH_STOCKIN_FAILURE';
 export const FETCH_STOCKIN_LOADING = 'FETCH_STOCKIN_LOADING';
export const DELETE_STOCKIN_FAIL = 'DELETE_STOCKIN_FAIL';
export const DELETE_STOCKIN_SUCCESS = 'DELETE_STOCKIN_SUCCESS';
export const DELETE_STOCKIN_LOADING = 'DELETE_STOCKIN_LOADING';
export const UPDATE_STOCKIN_SUCCESS = 'UPDATE_STOCKIN_SUCCESS';
export const UPDATE_STOCKIN_ERROR = 'UPDATE_STOCKIN_ERROR';
export const UPDATE_STOCKIN_PENDING = 'UPDATE_STOCKIN_PENDING';

// stock in actions
export const CREATE_STOCKRETURN_PENDING = 'CREATE_STOCKRETURN_PENDING';
 export const CREATE_STOCKRETURN_SUCCESS = 'CREATE_STOCKRETURN_SUCCESS';
 export const CREATE_STOCKRETURN_ERROR = 'CREATE_STOCKRETURN_ERROR';
 export const FETCH_STOCKRETURN_SUCCESS = 'FETCH_STOCKRETURN_SUCCESS';
 export const FETCH_STOCKRETURN_FAILURE = 'FETCH_STOCKRETURN_FAILURE';
 export const FETCH_STOCKRETURN_LOADING = 'FETCH_STOCKRETURN_LOADING';
export const DELETE_STOCKRETURN_FAIL = 'DELETE_STOCKRETURN_FAIL';
export const DELETE_STOCKRETURN_SUCCESS = 'DELETE_STOCKRETURN_SUCCESS';
export const DELETE_STOCKRETURN_LOADING = 'DELETE_STOCKRETURN_LOADING';
export const UPDATE_STOCKRETURN_SUCCESS = 'UPDATE_STOCKRETURN_SUCCESS';
export const UPDATE_STOCKRETURN_ERROR = 'UPDATE_STOCKRETURN_ERROR';
export const UPDATE_STOCKRETURN_PENDING = 'UPDATE_STOCKRETURN_PENDING';


export const GET_STOCKOUT_NUMBER_SUCCESS ='GET_STOCKOUT_NUMBER_SUCCESS';
export const GET_STOCKIN_NUMBER_SUCCESS='GET_STOCKIN_NUMBER_SUCCESS';
export const GET_STOCKRETURN_NUMBER_SUCCESS='GET_STOCKRETURN_NUMBER_SUCCESS';

export const FETCH_USERS_PENDING='FETCH_USERS_PENDING'
export const FETCH_USERS_ERROR='FETCH_USERS_ERROR'
export const FETCH_USERS_SUCCESS='FETCH_USERS_SUCCESS'